# Generated by Django 5.0.6 on 2025-03-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
