# Generated by Django 5.0.6 on 2025-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_mgt', '0002_properties_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
