# Generated by Django 5.0.6 on 2025-03-05 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_mgt', '0003_properties_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi', models.TextField()),
                ('head', models.TextField()),
                ('body', models.TextField()),
                ('image', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_mgt.properties')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
