# Generated by Django 5.0.6 on 2025-03-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_mgt', '0004_services_alter_properties_price_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='time',
        ),
        migrations.AlterField(
            model_name='visits',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
