# Generated by Django 5.0.6 on 2025-03-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_mgt', '0005_remove_visits_time_alter_visits_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
