# Generated by Django 5.0.6 on 2025-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_mgt', '0008_properties_taken_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
