# Generated by Django 5.0.6 on 2025-06-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_mgt', '0009_application_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='dis_body',
            field=models.CharField(default='A Header', max_length=100),
        ),
    ]
