# Generated by Django 5.0.6 on 2025-06-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_mgt', '0010_services_dis_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='dis_body',
            field=models.TextField(default='A Header'),
        ),
    ]
